# Generated by Django 5.0.3 on 2024-04-09 13:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('question_type', models.CharField(choices=[('Theory', 'Theory'), ('Objectives', 'Objectives')], max_length=50)),
                ('duration', models.CharField(blank=True, choices=[('20', '20 Mins'), ('30', '30 Mins'), ('40', '40 Mins'), ('50', '50 Mins'), ('60', '60 Mins'), ('90', '90 Mins'), ('120', '120 Mins')], max_length=4, null=True)),
                ('date_of_exam', models.DateTimeField(auto_now=True, verbose_name='Date Of Exam')),
                ('total_score', models.CharField(choices=[('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%')], max_length=50)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.assessment')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(blank=True, max_length=50, null=True)),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question')),
                ('optionA', models.CharField(blank=True, max_length=50, null=True)),
                ('optionB', models.CharField(blank=True, max_length=50, null=True)),
                ('optionC', models.CharField(blank=True, max_length=50, null=True)),
                ('optionD', models.CharField(blank=True, max_length=50, null=True)),
                ('optionE', models.CharField(blank=True, max_length=50, null=True)),
                ('theory_Answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Theory Answer')),
                ('option_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('question_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
