# Generated by Django 5.0.3 on 2024-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_is_active_quizattempt'),
        ('student', '0002_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_classes',
            field=models.ManyToManyField(to='student.classname'),
        ),
    ]
