# Generated by Django 5.0.3 on 2024-04-12 16:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_available_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theory_Answer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Theory Answer'),
        ),
    ]
