# Generated by Django 5.0.3 on 2024-04-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_theory_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.CharField(blank=True, choices=[('1', '1 Mins'), ('20', '20 Mins'), ('30', '30 Mins'), ('40', '40 Mins'), ('50', '50 Mins'), ('60', '60 Mins'), ('90', '90 Mins'), ('120', '120 Mins')], max_length=4, null=True),
        ),
    ]
